sources:
  - name: bronze
    catalog: "{{ var('catalog_name') }}"
    schema: "{{ var('bronze_schema_name') }}"
    tables:
      - name: bronze_json_movies
        description: "This table contains the raw JSON data for movies, ingested from the source systems."
        columns:
          - name: tmdb_id
            description: "The unique identifier for the movie in the TMDB database."
          - name: title
            description: "The title of the movie."
          - name: year
            description: "The release year of the movie."
          - name: script
            description: "The script of the movie given as a list of script blocks."
          - name: character_to_actor
            description: "The mapping between the characters and actors of the movie."

      - name: bronze_searches
        description: "This table contains the raw data of movie searches made in the web application."
        columns:
          - name: search_id
            description: "The unique identifier for the search query."
          - name: searched_at
            description: "The timestamp when the search was performed."
          - name: query_text
            description: "The search query string used to find movies."
          - name: type_filters
            description: "The script block type filters applied to the search query. When null, it indicates that no type filters were applied."
          - name: result_count
            description: "The number of search results returned for the query."
          - name: session_id
            description: "The unique identifier for the user session during which the search was performed."
          - name: created_at
            description: "The timestamp when the search record was created in the database."
