movies_project:
  target: dev

  outputs:
    dev:
      type: databricks
      method: http
      catalog: "{{ var('catalog_name') }}"
      schema: "{{ var('schema_name') }}"

      http_path: /sql/1.0/warehouses/d050fd97b5b14e8e

      host: "{{ env_var('DBT_HOST') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"

    prod:
      type: databricks
      method: http
      catalog: "{{ var('catalog_name') }}"
      schema: "{{ var('schema_name') }}"

      http_path: /sql/1.0/warehouses/d050fd97b5b14e8e

      host: "{{ env_var('DBT_HOST') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
