name: 6. Build and deploy backend and frontend services

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    if: vars.DEPLOY_BACKEND_AND_FRONTEND == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: "./terraform/infrastructure"
        run: terraform init

      - name: Read Terraform outputs
        id: tf_outputs
        working-directory: "./terraform/infrastructure"
        run: |
          echo "backend_ecr_repository_url=$(terraform output -raw backend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "frontend_ecr_repository_url=$(terraform output -raw frontend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "role_for_infrastructure_update=$(terraform output -raw role_for_infrastructure_update)" >> $GITHUB_OUTPUT
          echo "backend_instance_id=$(terraform output -raw backend_instance_id)" >> $GITHUB_OUTPUT
          echo "frontend_instance_id=$(terraform output -raw frontend_instance_id)" >> $GITHUB_OUTPUT
          echo "pg_port=$(terraform output -raw pg_port)" >> $GITHUB_OUTPUT
          echo "backend_log_group=$(terraform output -raw backend_log_group)" >> $GITHUB_OUTPUT
          echo "frontend_log_group=$(terraform output -raw frontend_log_group)" >> $GITHUB_OUTPUT
          echo "aws_region=$(terraform output -raw aws_region)" >> $GITHUB_OUTPUT

      - name: Read backend version from file
        run: echo "BACKEND_VERSION=$(cat app/backend/VERSION)" >> $GITHUB_ENV

      - name: Read frontend version from file
        run: echo "FRONTEND_VERSION=$(cat app/frontend/VERSION)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ steps.tf_outputs.outputs.role_for_infrastructure_update }}
          aws-region: ${{ steps.tf_outputs.outputs.aws_region }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set backend image tags
        id: set_backend_tags
        run: |
          BACKEND_TAGS="${{ steps.tf_outputs.outputs.backend_ecr_repository_url }}:${BACKEND_VERSION}"
          BACKEND_TAGS="$BACKEND_TAGS,${{ steps.tf_outputs.outputs.backend_ecr_repository_url }}:latest"
          echo "backend_tags=$BACKEND_TAGS" >> $GITHUB_OUTPUT

      - name: Set frontend image tags
        id: set_frontend_tags
        run: |
          FRONTEND_TAGS="${{ steps.tf_outputs.outputs.frontend_ecr_repository_url }}:${FRONTEND_VERSION}"
          FRONTEND_TAGS="$FRONTEND_TAGS,${{ steps.tf_outputs.outputs.frontend_ecr_repository_url }}:latest"
          echo "frontend_tags=$FRONTEND_TAGS" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./app/backend
          file: ./app/backend/Dockerfile
          push: true
          tags: ${{ steps.set_backend_tags.outputs.backend_tags }}
          provenance: false
          platforms: linux/amd64

      - name: Build and push frontend image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./app/frontend
          file: ./app/frontend/Dockerfile
          push: true
          tags: ${{ steps.set_frontend_tags.outputs.frontend_tags }}
          provenance: false
          platforms: linux/amd64

      - name: Deploy backend
        env:
          REGION: ${{ steps.tf_outputs.outputs.aws_region }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region $REGION \
            --instance-ids ${{ steps.tf_outputs.outputs.backend_instance_id }} \
            --document-name "AWS-RunShellScript" \
            --query "Command.CommandId" \
            --output text \
            --parameters 'commands=[
              "PG_HOST=$(aws ssm get-parameter --name /movies/PG_HOST --with-decryption --query Parameter.Value --output text --region ${{ steps.tf_outputs.outputs.aws_region }}) && \
              docker stop backend || true && \
              docker rm backend || true && \
              docker pull ${{ steps.tf_outputs.outputs.backend_ecr_repository_url }}:latest && \
              docker run -d --name backend --restart always -p 5000:5000 \
                -e PG_HOST=$PG_HOST \
                -e PG_PORT=${{ steps.tf_outputs.outputs.pg_port }} \
                -e PG_DATABASE=${{ secrets.PG_DATABASE }} \
                -e PG_USER=${{ secrets.PG_USER }} \
                -e PG_PASSWORD=${{ secrets.PG_PASSWORD }} \
                --log-driver=awslogs \
                --log-opt awslogs-region=$REGION \
                --log-opt awslogs-group=${{ steps.tf_outputs.outputs.backend_log_group }} \
                ${{ steps.tf_outputs.outputs.backend_ecr_repository_url }}:latest"
            ]')

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.tf_outputs.outputs.backend_instance_id }} \
            --region $REGION || true
          
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.tf_outputs.outputs.backend_instance_id }} \
            --region $REGION \
            --query '{Status:Status,Stdout:StandardOutputContent,Stderr:StandardErrorContent}' \
            --output json

      - name: Deploy frontend
        env:
          REGION: ${{ steps.tf_outputs.outputs.aws_region }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region $REGION \
            --instance-ids ${{ steps.tf_outputs.outputs.frontend_instance_id }} \
            --document-name "AWS-RunShellScript" \
            --query "Command.CommandId" \
            --output text \
            --parameters 'commands=[
              "docker stop frontend || true",
              "docker rm frontend || true",
              "docker pull ${{ steps.tf_outputs.outputs.frontend_ecr_repository_url }}:latest",
              "docker run -d --name frontend --restart always -p 80:80 \
                --log-driver=awslogs \
                --log-opt awslogs-region=$REGION \
                --log-opt awslogs-group=${{ steps.tf_outputs.outputs.frontend_log_group }}\
                ${{ steps.tf_outputs.outputs.frontend_ecr_repository_url }}:latest"
            ]')

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.tf_outputs.outputs.frontend_instance_id }}
            --region $REGION || true

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ steps.tf_outputs.outputs.frontend_instance_id }} \
            --region $REGION \
            --query '{Status:Status,Stdout:StandardOutputContent,Stderr:StandardErrorContent}' \
            --output json
