name: ci-cd

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  detect_changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      ingestion: ${{ steps.filter.outputs.ingestion }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ingestion:
              - 'ingestion/**'

  run_tests:
    needs: detect_changes
    if: needs.detect_changes.outputs.ingestion == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        working-directory: "./ingestion"
        run: |
          pip install poetry
          poetry install --no-root --with dev

      - name: Run unit tests
        working-directory: "./ingestion"
        run: |
          poetry run pytest --cov=src --cov-report=term-missing

  permissions_for_github_actions:
    runs-on: ubuntu-latest
    name: "Permissions for Github Actions"
    outputs:
      github_actions_role_for_infrastructure_arn: ${{ steps.set_outputs.outputs.github_actions_role_for_infrastructure_arn }}
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      # If local execution mode is set for the workspace
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: "./terraform/permissions_for_github_actions"
        run: terraform init

      - name: Terraform Plan
        working-directory: "./terraform/permissions_for_github_actions"
        run: terraform plan

      - name: Terraform Apply
        id: apply_permissions_for_github_actions
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: "./terraform/permissions_for_github_actions"
        run: terraform apply -auto-approve

      - name: Set outputs
        id: set_outputs
        working-directory: "./terraform/permissions_for_github_actions"
        run: |
          echo "github_actions_role_for_infrastructure_arn=$(terraform output -raw github_actions_role_for_infrastructure_arn)" >> $GITHUB_OUTPUT

  terraform_infrastructure:
    needs: permissions_for_github_actions
    runs-on: ubuntu-latest
    name: "Terraform Infrastructure"
    outputs:
      ingestion_ecr_repository_url: ${{ steps.set_outputs.outputs.ingestion_ecr_repository_url }}
      backend_ecr_repository_url: ${{ steps.set_outputs.outputs.backend_ecr_repository_url }}
      frontend_ecr_repository_url: ${{ steps.set_outputs.outputs.frontend_ecr_repository_url }}
      github_actions_role_arn: ${{ steps.set_outputs.outputs.github_actions_role_arn }}
      ingestion_lambda_function_name: ${{ steps.set_outputs.outputs.ingestion_lambda_function_name }}
      movies_s3_bucket_name: ${{ steps.set_outputs.outputs.movies_s3_bucket_name }}
      pg_port: ${{ steps.set_outputs.outputs.pg_port }}
      alb_url: ${{ steps.set_outputs.outputs.alb_url }}
      ecs_cluster_name: ${{ steps.set_outputs.outputs.ecs_cluster_name }}
      backend_ecs_task_definition_family: ${{ steps.set_outputs.outputs.backend_ecs_task_definition_family }}
      frontend_ecs_task_definition_family: ${{ steps.set_outputs.outputs.frontend_ecs_task_definition_family }}
      backend_ecs_service_name: ${{ steps.set_outputs.outputs.backend_ecs_service_name }}
      frontend_ecs_service_name: ${{ steps.set_outputs.outputs.frontend_ecs_service_name }}
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ needs.permissions_for_github_actions.outputs.github_actions_role_for_infrastructure_arn }}
          aws-region: us-east-1
          mask-aws-account-id: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: "./terraform/infrastructure"
        run: terraform init

      - name: Terraform Get
        working-directory: "./terraform/infrastructure"
        run: terraform get

      - name: Terraform Plan
        working-directory: "./terraform/infrastructure"
        run: terraform plan --var "pg_database=${{ secrets.PG_DATABASE }}" --var "pg_user=${{ secrets.PG_USER }}" --var "pg_password=${{ secrets.PG_PASSWORD }}"

      - name: Terraform Apply
        id: apply_infrastructure
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: "./terraform/infrastructure"
        run: terraform apply -auto-approve --var "pg_database=${{ secrets.PG_DATABASE }}" --var "pg_user=${{ secrets.PG_USER }}" --var "pg_password=${{ secrets.PG_PASSWORD }}"

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Create secret scope in Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks secrets create-scope secret-scope || echo "Scope already exists"

      - name: Set outputs
        id: set_outputs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        working-directory: "./terraform/infrastructure"
        run: |
          echo "ingestion_ecr_repository_url=$(terraform output -raw ingestion_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "backend_ecr_repository_url=$(terraform output -raw backend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "frontend_ecr_repository_url=$(terraform output -raw frontend_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "github_actions_role_arn=$(terraform output -raw github_actions_role_arn)" >> $GITHUB_OUTPUT
          echo "ingestion_lambda_function_name=$(terraform output -raw ingestion_lambda_function_name)" >> $GITHUB_OUTPUT
          echo "movies_s3_bucket_name=$(terraform output -raw movies_s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "pg_port=$(terraform output -raw pg_port)" >> $GITHUB_OUTPUT
          PG_HOST=$(terraform output -raw pg_host)
          echo "::add-mask::$PG_HOST"
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_host","string_value":"'"$PG_HOST"'"}'
          echo "alb_url=$(terraform output -raw alb_url)" >> $GITHUB_OUTPUT
          echo "ecs_cluster_name=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "backend_ecs_task_definition_family=$(terraform output -raw backend_ecs_task_definition_family)" >> $GITHUB_OUTPUT
          echo "frontend_ecs_task_definition_family=$(terraform output -raw frontend_ecs_task_definition_family)" >> $GITHUB_OUTPUT
          echo "backend_ecs_service_name=$(terraform output -raw backend_ecs_service_name)" >> $GITHUB_OUTPUT
          echo "frontend_ecs_service_name=$(terraform output -raw frontend_ecs_service_name)" >> $GITHUB_OUTPUT

  build:
    needs: [permissions_for_github_actions, terraform_infrastructure]
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      - name: Read ingestion version from file
        id: get_ingestion_version
        run: echo "INGESTION_VERSION=$(cat ingestion/VERSION)" >> $GITHUB_ENV

      - name: Read backend version from file
        id: get_backend_version
        run: echo "BACKEND_VERSION=$(cat app/backend/VERSION)" >> $GITHUB_ENV

      - name: Read frontend version from file
        id: get_frontend_version
        run: echo "FRONTEND_VERSION=$(cat app/frontend/VERSION)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ needs.terraform_infrastructure.outputs.github_actions_role_arn }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set ingestion image tags
        id: set_ingestion_tags
        run: |
          INGESTION_TAGS="${{ needs.terraform_infrastructure.outputs.ingestion_ecr_repository_url }}:${INGESTION_VERSION}"
          INGESTION_TAGS="$INGESTION_TAGS,${{ needs.terraform_infrastructure.outputs.ingestion_ecr_repository_url }}:latest"
          echo "ingestion_tags=$INGESTION_TAGS" >> $GITHUB_OUTPUT

      - name: Set backend image tags
        id: set_backend_tags
        run: |
          BACKEND_TAGS="${{ needs.terraform_infrastructure.outputs.backend_ecr_repository_url }}:${BACKEND_VERSION}"
          BACKEND_TAGS="$BACKEND_TAGS,${{ needs.terraform_infrastructure.outputs.backend_ecr_repository_url }}:latest"
          echo "backend_tags=$BACKEND_TAGS" >> $GITHUB_OUTPUT

      - name: Set frontend image tags
        id: set_frontend_tags
        run: |
          FRONTEND_TAGS="${{ needs.terraform_infrastructure.outputs.frontend_ecr_repository_url }}:${FRONTEND_VERSION}"
          FRONTEND_TAGS="$FRONTEND_TAGS,${{ needs.terraform_infrastructure.outputs.frontend_ecr_repository_url }}:latest"
          echo "frontend_tags=$FRONTEND_TAGS" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ingestion image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./ingestion
          file: ./ingestion/Dockerfile
          push: true
          tags: ${{ steps.set_ingestion_tags.outputs.ingestion_tags }}
          provenance: false
          platforms: linux/arm64
          build-args: |
            DATABRICKS_MOVIE_DATA_VOLUME_PATH=${{ vars.DATABRICKS_MOVIE_DATA_VOLUME_PATH }}

      - name: Build and push backend image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./app/backend
          file: ./app/backend/Dockerfile
          push: true
          tags: ${{ steps.set_backend_tags.outputs.backend_tags }}
          provenance: false
          platforms: linux/amd64

      - name: Build and push frontend image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./app/frontend
          file: ./app/frontend/Dockerfile
          push: true
          tags: ${{ steps.set_frontend_tags.outputs.frontend_tags }}
          provenance: false
          platforms: linux/amd64

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ needs.terraform_infrastructure.outputs.ingestion_lambda_function_name }} \
            --image-uri ${{ needs.terraform_infrastructure.outputs.ingestion_ecr_repository_url }}:latest

      - name: Wait for Lambda code update to finish
        run: |
          aws lambda wait function-updated \
            --function-name ${{ needs.terraform_infrastructure.outputs.ingestion_lambda_function_name }}

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Get pg_host from Databricks secrets
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          PG_HOST=$(databricks secrets get-secret secret-scope pg_host | jq -r .value | base64 --decode)
          echo "PG_HOST=$PG_HOST" >> $GITHUB_ENV
          echo "::add-mask::$PG_HOST"

      - name: Update Lambda function environment variables
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          PG_HOST: ${{ env.PG_HOST }}
          PG_PORT: ${{ needs.terraform_infrastructure.outputs.pg_port }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ needs.terraform_infrastructure.outputs.ingestion_lambda_function_name }} \
            --environment "Variables={TMDB_API_KEY=$TMDB_API_KEY,DATABRICKS_HOST=$DATABRICKS_HOST,DATABRICKS_TOKEN=$DATABRICKS_TOKEN,PG_HOST=$PG_HOST,PG_PORT=$PG_PORT,PG_DATABASE=$PG_DATABASE,PG_USER=$PG_USER,PG_PASSWORD=$PG_PASSWORD}"

      - name: Wait for Lambda configuration update to finish
        run: |
          aws lambda wait function-updated \
            --function-name ${{ needs.terraform_infrastructure.outputs.ingestion_lambda_function_name }}

      - name: Update image of backend ECS task
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ needs.terraform_infrastructure.outputs.backend_ecs_task_definition_family }} \
            --query taskDefinition \
          | jq '
            del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
            )
            | .containerDefinitions[0].image = "'"${{ needs.terraform_infrastructure.outputs.backend_ecr_repository_url }}:latest"'"
          ' > updated-task-def.json
  
          aws ecs register-task-definition \
            --cli-input-json file://updated-task-def.json

      - name: Update service to use new backend task definition
        run: |
          aws ecs update-service \
            --cluster ${{ needs.terraform_infrastructure.outputs.ecs_cluster_name }} \
            --service ${{ needs.terraform_infrastructure.outputs.backend_ecs_service_name }} \
            --force-new-deployment

      - name: Wait for backend service stability
        run: |
          aws ecs wait services-stable \
            --cluster ${{ needs.terraform_infrastructure.outputs.ecs_cluster_name }} \
            --services ${{ needs.terraform_infrastructure.outputs.backend_ecs_service_name }}

      - name: Update image of frontend ECS task
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ needs.terraform_infrastructure.outputs.frontend_ecs_task_definition_family }} \
            --query taskDefinition \
          | jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
            | .containerDefinitions[0].image = "'"${{ needs.terraform_infrastructure.outputs.frontend_ecr_repository_url }}:latest"'"
          ' > updated-task-def.json

          aws ecs register-task-definition \
            --cli-input-json file://updated-task-def.json

      - name: Update service to use new frontend task definition
        run: |
          aws ecs update-service \
            --cluster ${{ needs.terraform_infrastructure.outputs.ecs_cluster_name }} \
            --service ${{ needs.terraform_infrastructure.outputs.frontend_ecs_service_name }} \
            --force-new-deployment

      - name: Wait for frontend service stability
        run: |
          aws ecs wait services-stable \
            --cluster ${{ needs.terraform_infrastructure.outputs.ecs_cluster_name }} \
            --services ${{ needs.terraform_infrastructure.outputs.frontend_ecs_service_name }}

  deploy_asset_bundle:
    needs: [permissions_for_github_actions, terraform_infrastructure]
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set AWS keys and PostgreSQL db info as Databricks secrets
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PG_PORT: ${{ needs.terraform_infrastructure.outputs.pg_port }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"aws_access_key_id","string_value":"'"$AWS_ACCESS_KEY_ID"'"}'
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"aws_secret_access_key","string_value":"'"$AWS_SECRET_ACCESS_KEY"'"}'
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_port","string_value":"'"$PG_PORT"'"}'
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_database","string_value":"'"$PG_DATABASE"'"}'
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_user","string_value":"'"$PG_USER"'"}'
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_password","string_value":"'"$PG_PASSWORD"'"}'

      - name: Deploy movies asset bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          BUNDLE_VAR_movie_data_volume_path: ${{ vars.DATABRICKS_MOVIE_DATA_VOLUME_PATH }}
          BUNDLE_VAR_secret_scope: "secret-scope"
          BUNDLE_VAR_s3_bucket_name: ${{ needs.terraform_infrastructure.outputs.movies_s3_bucket_name }}
        working-directory: "./movies_asset_bundle"
        run: |
          databricks bundle deploy -t prod
