name: Build and deploy extraction service

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Create secret scope in Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks secrets create-scope secret-scope || echo "Scope already exists"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        working-directory: "./terraform/infrastructure"
        run: terraform init

      - name: Read Terraform outputs
        id: tf_outputs
        working-directory: "./terraform/infrastructure"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "extraction_ecr_repository_url=$(terraform output -raw extraction_ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "role_for_infrastructure_update=$(terraform output -raw role_for_infrastructure_update)" >> $GITHUB_OUTPUT
          echo "extraction_lambda_function_name=$(terraform output -raw extraction_lambda_function_name)" >> $GITHUB_OUTPUT
          echo "pg_port=$(terraform output -raw pg_port)" >> $GITHUB_OUTPUT
          PG_HOST=$(terraform output -raw pg_host)
          echo "::add-mask::$PG_HOST"
          databricks secrets put-secret --json '{"scope":"secret-scope","key":"pg_host","string_value":"'"$PG_HOST"'"}'

      - name: Read version from file
        run: echo "INGESTION_VERSION=$(cat extraction/VERSION)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ steps.tf_outputs.outputs.role_for_infrastructure_update }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: set_tags
        run: |
          TAGS="${{ steps.tf_outputs.outputs.extraction_ecr_repository_url }}:${INGESTION_VERSION}"
          TAGS="$TAGS,${{ steps.tf_outputs.outputs.extraction_ecr_repository_url }}:latest"
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./extraction
          file: ./extraction/Dockerfile
          push: true
          tags: ${{ steps.set_tags.outputs.tags }}
          provenance: false
          platforms: linux/arm64
          build-args: |
            DATABRICKS_MOVIE_DATA_VOLUME_PATH=${{ vars.DATABRICKS_MOVIE_DATA_VOLUME_PATH }}

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ steps.tf_outputs.outputs.extraction_lambda_function_name }} \
            --image-uri ${{ steps.tf_outputs.outputs.extraction_ecr_repository_url }}:latest

      - name: Wait for Lambda code update to finish
        run: |
          aws lambda wait function-updated \
            --function-name ${{ steps.tf_outputs.outputs.extraction_lambda_function_name }}

      - name: Get pg_host from Databricks secrets
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          PG_HOST=$(databricks secrets get-secret secret-scope pg_host | jq -r .value | base64 --decode)
          echo "PG_HOST=$PG_HOST" >> $GITHUB_ENV
          echo "::add-mask::$PG_HOST"

      - name: Update Lambda function environment variables
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          PG_HOST: ${{ env.PG_HOST }}
          PG_PORT: ${{ steps.tf_outputs.outputs.pg_port }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ steps.tf_outputs.outputs.extraction_lambda_function_name }} \
            --environment "Variables={TMDB_API_KEY=$TMDB_API_KEY,DATABRICKS_HOST=$DATABRICKS_HOST,DATABRICKS_TOKEN=$DATABRICKS_TOKEN,PG_HOST=$PG_HOST,PG_PORT=$PG_PORT,PG_DATABASE=$PG_DATABASE,PG_USER=$PG_USER,PG_PASSWORD=$PG_PASSWORD}"

      - name: Wait for Lambda configuration update to finish
        run: |
          aws lambda wait function-updated \
            --function-name ${{ steps.tf_outputs.outputs.extraction_lambda_function_name }}
