name: prod-ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for next step
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: "./ingestion"
        run: |
          pip install poetry
          poetry install --with dev

      - name: Run unit tests
        working-directory: "./ingestion"
        run: |
          pytest --cov=src --cov-report=term-missin
